				<div class="span4">
					<div class="menu-section">
						<h3>Appetizers</h3>
						
						<h4>Chicken Fingers </h4>
						<div class="span12 nomargin">
							<p class="span11">Fresh chicken hand breaded and fried to perfection. Enjoy any style: buffalo, honey buffalo, BBQ, or teriyaki</p>
							<p class="span1">8</p>
						</div>
						
						<h4>Jalapeño Poppers</h4>
						<div class="span12 nomargin">
							<p class="span11">Jalapeños stuffed with cream cheese. Served with sour cream or your choice of dipping sauce</p>
							<p class="span1">7</p>
						</div>
						
						<h4>Potato Skins</h4>
						<div class="span12 nomargin">
							<p class="span11">Baked potatoes topped with melted cheese and bacon. Sour cream included on the side for dipping</p>
							<p class="span1">7</p>
						</div>
						
						<h4>Mozzarella Sticks</h4>
						<div class="span12 nomargin">
							<p class="span11">Breaded mozzarella cheese fried crispy and served with a marinara dipping sauce</p>
							<p class="span1">7</p>
						</div>
						
						<h4>Nachos Plain</h4>
						<div class="span12 nomargin">
							<p class="span11">Hand cut tortilla chips topped with mixed cheeses, tomatoes, olives, jalapeños, peppers & onions served with sour cream & salsa</p>
							<p class="span1">7</p>
							
							<div class="row-fluid">
								<p class="span4">Add Chicken (9)</p>
								<p class="span4">Add Chili (9)</p>
								<p class="span4">Add Steak (10)</p>
							</div>
						</div>
						
						<h4>Quesadillas</h4>
						<div class="span12 nomargin">
							<p class="span11">Flour tortilla stuffed with peppers, onions, and tomatoes & mixed cheese served with salsa and sour cream on the side</p>

							<div class="row-fluid">
								<p class="span4">Steak (10)</p>
								<p class="span4">Vegetable (7)</p>
								<p class="span4">Chicken (8)</p>
							</div>													
						</div>
						
						<h4>Wings</h4>
						<div class="span12 nomargin">
							<p class="span11">Fresh chicken wings fried to order. Enjoy any style: Buffalo, Honey Buffalo, BBQ, or Teriyaki</p>
							<p class="span1">7</p>
						</div>
						
						<h4>Chips and Salsa </h4>
						<div class="span12 nomargin">
							<p class="span11">Hand cut flour tortillas fried to perfection and served with salsa</p>
							<p class="span1">4</p>
						</div>
						
						<h4>Fried Pickles</h4>
						<div class="span12 nomargin">
							<p class="span11">Freshly sliced pickles battered in flour and fried</p>
							<p class="span1">5</p>
						</div>
						
						<h4>Side of French Fries </h4>
						<div class="span12 nomargin">
							<p class="span11">16 ounces of hand cut fries , lightly salted and fried to perfection</p>
							<p class="span1">4</p>
						</div>
						
						
						<div class="span12 nomargin">
							<div class="span11"><h4>Seasoned Fries</h4></div>
							<p class="span1">5</p>
						</div>
						
						<h4>Side of Onion Rings</h4>
						<div class="span12 nomargin">
							<p class="span11">16 ounces of thick fried onion rings</p>
							<p class="span1">6</p>
						</div>																																										
					</div>
					
					<div class="menu-section">
						
						<div class="span12 nomargin">
							<h3 class="span9">Soup</h3>
							<div class="span3 price-type">CUP/BOWL</div>
						</div>
						
						<h4>Pickled O’s Famous Clam Chowder</h4>
						<div class="span12 nomargin">
							<p class="span11">Award winning New England style clam chowder</p>
							<p class="span1">4/6</p>
						</div>
						
						<h4>Chili</h4>
						<div class="span12 nomargin">
							<p class="span11">Topped with mixed cheeses alongside Pickled O’s homemade tortilla chips</p>
							<p class="span1">4/6</p>
						</div>
					</div>
					<div class="menu-section">
						
						<div class="span12 nomargin">
							<h3 class="span9">Salad</h3>
							<div class="span3 price-type">SM/LG</div>
						</div>
						
						<h4>House Garden Salad </h4>
						<div class="span12 nomargin">
							<p class="span11">Mixed greens, fresh vegetables with your choice of dressing on the side</p>
							<p class="span1">3</p>
						</div>
						
						<h4>House with Grilled Chicken</h4>
						<div class="span12 nomargin">
							<p class="span11">Pickled O's house salad topped with fresh chicken</p>
							<p class="span1">10</p>
						</div>
						
						<h4>House with Pickled O’s Marinated Steak Tips</h4>
						<div class="span12 nomargin">
							<p class="span11">Pickled O’s house salad topped with Pickled O’s famous steak tips cooked to order</p>
							<p class="span1">13</p>
						</div>
						
						<h4>Caesar</h4>
						<div class="span12 nomargin">
							<p class="span11">Romaine lettuce with Parmesan cheese, multi-grain croutons, and Caesar dressing</p>
							<p class="span1">4/8</p>
						</div>
						
						<h4>Caesar with Grilled Chicken</h4>
						<div class="span12 nomargin">
							<p class="span11">Pickled O’s Caesar salad topped with fresh chicken cooked to order</p>
							<p class="span1">11</p>
						</div>
						
						<h4>Caesar with Marinated Steak Tips</h4>
						<div class="span12 nomargin">
							<p class="span11">Pickled O’s Caesar salad topped with Pickled O’s famous steak tips cooked to order</p>
							<p class="span1">13</p>
						</div>
						<div class="span12 center">
							<p class="menuNotes">Salad Dressings: Italian, Creamy Italian, Caesar, Parmesan Peppercorn, Bleu Cheese,Balsamic Vinaigrette, Ranch, Russian, and Honey Mustard</p>
						</div>										
						
					</div>					
				</div>
				<div class="span4">
					<div class="menu-section">
						<h3>Sandwiches & Wraps</h3>
						<div class="span12 center">
							<p class="menuNotes">All sandwiches and wraps come with homemade french fries. Fries may be substituted for seasoned french fries or onion rings for an additional $1. Any additional toppings can be added to the sandwiches/wraps for $.50 each</p>
						</div>							
						
						<h4>Hamburger</h4>
						<div class="span12 nomargin">
							<p class="span11">½ pound burger topped with lettuce, tomato, and red onion on a butter toasted bun</p>
							<p class="span1">8</p>
						</div>
						
						<h4>Pickled O' Burger</h4>
						<div class="span12 nomargin">
							<p class="span11">½ pound burger topped with American cheese, bacon, BBQ sauce, lettuce, tomato, and sauteed peppers, onions and mushrooms on a butter toasted bun. (No Substitution)</p>
							<p class="span1">10</p>
						</div>
						
						<h4>Boca Burger</h4>
						<div class="span12 nomargin">
							<p class="span11">Vegetarian burger topped with lettuce, tomato, and red onion on a butter toasted bun</p>
							<p class="span1">9</p>
						</div>
						
						<h4>Chicken Sandwich (Plain, Buffalo, BBQ, or Teriyaki)</h4>
						<div class="span12 nomargin">
							<p class="span11">6 ounce chicken breast topped with lettuce, tomato, and red onion on a butter toasted bun</p>
							<p class="span1">9</p>
						</div>
						
						<h4>Chicken Caesar Wrap</h4>
						<div class="span12 nomargin">
							<p class="span11">6 ounce chicken breast with romaine lettuce, Parmesan cheese, and caesar dressing served in a toasted wrap</p>
							<p class="span1">9</p>
						</div>
						
						<h4>Seasoned Chicken Burger</h4>
						<div class="span12 nomargin">
							<p class="span11">6 ounce of seasoned chicken patty on a butter toasted bun</p>
							<p class="span1">9</p>
						</div>
						<h4>Turkey Club</h4>
						<div class="span12 nomargin">
							<p class="span11">All natural oven roasted turkey breast sliced thin with lettuce, tomato, bacon and mayonnaise</p>
							<p class="span1">9</p>
						</div>
						<h4>B.L.T.</h4>
						<div class="span12 nomargin">
							<p class="span11">Bacon, lettuce, tomato, and mayonnaise on your choice of bread</p>
							<p class="span1">9</p>
						</div>
						<h4>Steak Tip Sub</h4>
						<div class="span12 nomargin">
							<p class="span11">Pickled O’s marinated steak tips with American cheese stuffed in a sub roll</p>
							<p class="span1">9</p>
						</div>
						<h4>Veggie Wrap</h4>
						<div class="span12 nomargin">
							<p class="span11">Sauteed stir fry mix, lettuce, tomato, and ranch dressing in a toasted wrap</p>
							<p class="span1">8</p>
						</div>
						<h4>Turkey Bacon Cheddar</h4>
						<div class="span12 nomargin">
							<p class="span11">Sliced oven roasted turkey breast with bacon, tomato, and cheddar cheese</p>
							<p class="span1">9</p>
						</div>
						<h4>Turkey Reuben Toastie</h4>
						<div class="span12 nomargin">
							<p class="span11">Sliced oven roasted turkey breast topped with sauerkraut, Swiss cheese, and Russian dressing on rye bread</p>
							<p class="span1">9</p>
						</div>
						<h4>Tomato, Onion, Cheddar Toastie</h4>
						<div class="span12 nomargin">
							<p class="span11">Sliced tomato and red onion topped with cheddar cheese on your choice of bread</p>
							<p class="span1">8</p>
						</div>

						<h4>Hot Pastrami Sandwich</h4>
						<div class="span12 nomargin">
							<p class="span11">Hot pastrami with Swiss cheese on a butter toasted bun topped with lettuce, tomato, and red onion</p>
							<p class="span1">9</p>
						</div>
						<h4>Pulled Pork Sandwich </h4>
						<div class="span12 nomargin">
							<p class="span11">Hickory smoked pulled pork on a butter toasted bun with lettuce, tomato, and red onion</p>
							<p class="span1">9</p>
						</div>
						<h4>Steak Bomb Wrap/or Sub</h4>
						<div class="span12 nomargin">
							<p class="span11">Shaved steak topped with melted cheese, grilled peppers, onions & mushrooms on a sub roll or wrap</p>
							<p class="span1">9</p>
						</div>																																																																								
					</div>						
				</div>		
				<div class="span4">
					<div class="menu-section">
						<h3>Entrees</h3>
						<div class="span12 center">
							<p class="menuNotes">All entrees come with your choice of rice, mashed potatoes, or homemade french fries. Fries may be substituted for seasoned french fries or onion rings for an additional $1. The Shepard’s Pie, Beef Stew, and Stir Fry’s do not come with an additional side.</p>
						</div>
												
						<h4>Shepard’s Pie</h4>
						<div class="span12 nomargin">
							<p class="span11">A mix of ground beef, peas, and carrots topped with mashed potatoes and melted mixed cheese</p>
							<p class="span1">10</p>
						</div>
						
						<h4>Steak Tips</h4>
						<div class="span12 nomargin">
							<p class="span11">12 ounces of Pickled O’s house marinated steak tips served with fresh mixed vegetables and your choice of a side</p>
							<p class="span1">Market Price</p>
						</div>
						
						<h4>Fish & Chips</h4>
						<div class="span12 nomargin">
							<p class="span11">Fresh haddock battered and fried to perfection. Served with french fries, coleslaw and tartar sauce</p>
							<p class="span1">12</p>
						</div>
						
						<h4>Baked Haddock</h4>
						<div class="span12 nomargin">
							<p class="span11">12 ounces of haddock baked with a cracker crumb topping</p>
							<p class="span1">Market Price</p>
						</div>
						
						<h4>Vegetable Stir Fry</h4>
						<div class="span12 nomargin">
							<p class="span11">Sauteed vegetable medley served over a bed of rice with stir fry sauce</p>
							<p class="span1">9</p>
						</div>
						
						<h4>Chicken Stir Fry</h4>
						<div class="span12 nomargin">
							<p class="span11">Pickled O’s vegetable stir fry with fresh grilled chicken</p>
							<p class="span1">11</p>
						</div>
						
						<h4>Grilled Combo</h4>
						<div class="span12 nomargin">
							<p class="span11">Steak tips and grilled chicken</p>
							<p class="span1">15</p>
						</div>																		
					</div>
					<div class="menu-section">
						<h3>Kids Menu</h3>
						<div class="span12 center">
							<p class="menuNotes">All kids meals, excluding the kids pizza, come with homemade french fries</p>
						</div>
												
						
						<div class="span12 nomargin">
							<div class="span11"><h4>Kids Cheese Pizza</h4></div>
							<p class="span1">5</p>
						</div>
						
						<div class="span12 nomargin">
							<div class="span11"><h4>Kids Chicken Fingers</h4></div>
							<p class="span1">6</p>
						</div>

						<div class="span12 nomargin">
							<div class="span11"><h4>Kids Cheeseburger</h4></div>
							<p class="span1">6</p>
						</div>

						<div class="span12 nomargin">
							<div class="span11"><h4>Kids Grilled Cheese</h4></div>
							<p class="span1">6</p>
						</div>																														
					</div>	
					<div class="menu-section">
						<h3>Desserts</h3>												
						
						<h4>Warm Apple Pie a La Mode</h4>
						<div class="span12 nomargin">
							<p class="span11">Warm apple pie with vanilla ice cream, whipped cream and chocolate syrup</p>
							<p class="span1">4</p>
						</div>
						
						<h4>Brownie Sundae</h4>
						<div class="span12 nomargin">
							<p class="span11">Warm brownie with vanilla ice cream, whipped cream and chocolate syrup</p>
							<p class="span1">4</p>
						</div>
																													
					</div>														
				</div>		